language: node_js
cache:
  directories:
    - ~/.npm
node_js:
  - stable
notifications:
  email:
    recipients:
      - ashik9591@gmail.com
    on_success: always
    on_failure: always
git:
  depth: 3
script:
  - npm run build